apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ template "geoServer.fullname" . }}-request-api-auth
spec:
  jwtRules:
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: >-
        https://platform-keycloak.{{.Values.dnsWildcard }}/auth/realms/{{ .Release.Namespace }}-officer-portal
      jwksUri: >-
        https://platform-keycloak.{{.Values.dnsWildcard }}/auth/realms/{{ .Release.Namespace }}-officer-portal/protocol/openid-connect/certs
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: >-
        https://platform-keycloak.{{.Values.dnsWildcard }}/auth/realms/{{ .Release.Namespace }}-citizen-portal
      jwksUri: >-
        https://platform-keycloak.{{.Values.dnsWildcard }}/auth/realms/{{ .Release.Namespace }}-citizen-portal/protocol/openid-connect/certs
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: >-
        https://platform-keycloak.{{.Values.dnsWildcard }}/auth/realms/{{ .Release.Namespace }}-external-system
      jwksUri: >-
        https://platform-keycloak.{{.Values.dnsWildcard }}/auth/realms/{{ .Release.Namespace }}-external-system/protocol/openid-connect/certs
  selector:
    matchLabels:
        {{- include "geoServer.labels" . | nindent 8 }}