apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "geoServer.labels" . | nindent 4 }}
  name: {{ template "geoServer.name" . }}
spec:
  host: {{ template "geoServer.hostname" . }}
  path: /geoserver
  port:
    targetPort: {{ .Values.geoServer.service.portName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "geoServer.name" . }}
    weight: 100
  wildcardPolicy: None