{{- if .Values.geoServer.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoServer.serviceAccountName" . }}
  labels:
    {{- include "geoServer.labels" . | nindent 4 }}
{{- end }}